/** @tailwind 3.x config — autogenerated */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          blue:  '#1360C5',
          teal:  '#0093B2',
          cyan:  '#78E5F3',
          violet:'#7F36F4',
          surface:'#F2F4F7',
        },
      },
      fontFamily: { sans: ['Inter','Roboto','Helvetica','Arial','sans-serif'] },
      borderRadius: { card:'12px', section:'22px', pill:'9999px' },
      borderWidth: { '1.5':'1.5px', '3':'3px' },
    },
  },
  plugins: [],
};