const OPTIMIZER_COPY = {
    stepper: {
        addMeals: 'Add meals',
        pickGoal: 'Pick a goal',
        adjustLimits: 'Adjust limits',
        generatePlan: 'Generate plan',
        reviewSave: 'Review and save',
    },
    buttons: {
        generatePlan: 'Generate plan',
        pickGoal: 'Pick a goal',
        quickTour: 'Quick tour',
        addMeals: 'Add meals',
        addMeal: 'Add meal',
        importCsv: 'Import CSV',
        loadSamples: 'Load sample meals',
        savePlan: 'Save plan',
        saveThisPlan: 'Save this plan',
        runAgain: 'Run again',
        export: 'Export',
        addRule: 'Add rule',
    },
    sections: {
        planSettings: 'Plan settings',
        nextStep: 'Next step',
        planSummary: 'Plan summary',
        nutritionLimits: 'Nutrition limits (advanced)',
        varietyRules: 'Variety rules (advanced)',
        optimizationResults: 'Optimization Results',
    },
    labels: {
        targetsAchievable: 'Targets achievable',
        mealsThatFit: 'Meals that fit your rules',
        needsInfo: 'Needs info',
        needsAttention: 'Needs attention',
        fitsRules: 'Fits rules',
        warnings: 'Warnings',
        goal: 'Goal',
        planLength: 'Plan length',
        mealsPerDay: 'Meals per day',
        maxRepeats: 'Max repeats per meal',
        dailyCalories: 'Daily calories',
        proteinPerDay: 'Protein per day (g)',
        carbsPerDay: 'Carbs per day (g)',
        fatPerDay: 'Fat per day (g)',
        sodiumPerDay: 'Sodium per day (mg)',
    },
    helper: {
        goalDescriptions: {
            Cut: 'Fewer calories, higher protein.',
            Maintain: 'Stable calories and macros.',
            Bulk: 'More calories and protein.',
            Custom: 'Set your own targets.',
        },
        goalPrompt: 'Pick a goal to get started.',
        generatePlanDisabled: 'Pick a goal to generate a plan.',
        generatePlanHint: 'You can adjust limits after you pick a goal.',
    },
    status: {
        ready: 'Fits rules',
        missing: 'Needs info',
        outlier: 'Needs attention',
        duplicate: 'Needs attention',
        excluded: 'Excluded',
        error: 'Error',
    },
};

export default OPTIMIZER_COPY;
