// dark theme — autogenerated
import { createTheme } from '@mui/material/styles';
export default createTheme({
  palette: {
    mode: 'dark',
    primary: {
      light: '#8ad9f6',
      main: '#66c0f4',
      dark: '#3194c5',
    },
    secondary: {
      light: '#4abbd0',
      main: '#009fb7',
      dark: '#007a8c',
    },
    accent: { main: '#7F36F4' },
    background: { default:'#0A0C10', paper:'#12151B' },
    surface: { light:'#1E222B' },
    role: {
      admin: '#ef9a9a',
      user: '#90caf9',
      premium: '#ce93d8',
      super_admin: '#ffcc80'
    },
    state: {
      active: '#a5d6a7',
      pending: '#ffcc80',
      suspended: '#b39ddb',
      deleted: '#eeeeee',
      archived: '#bdbdbd'
    },
  },
  shape:{ borderRadius:12 },
  typography:{ fontFamily:'Inter,Roboto,Helvetica Neue,Helvetica,Arial,sans-serif' },
});