// dark theme — autogenerated
import { createTheme } from '@mui/material/styles';
export default createTheme({
  palette: {
    mode: 'dark',
    primary: { main: '#78E5F3' },
    secondary: { main: '#0093B2' },
    accent: { main: '#7F36F4' },
    background: { default:'#0B0D11', paper:'#12151B' },
    surface: { light:'#1E222B' },
  },
  shape:{ borderRadius:12 },
  typography:{ fontFamily:'Inter,Roboto,Helvetica Neue,Helvetica,Arial,sans-serif' },
});