// light theme — autogenerated
import { createTheme } from '@mui/material/styles';
export default createTheme({
  palette: {
    mode: 'light',
    primary: { main: '#1360C5' },
    secondary: { main: '#0093B2' },
    accent: { main: '#7F36F4' },
    background: { default:'#FFFFFF', paper:'#FFFFFF' },
    surface: { light:'#F2F4F7' },
  },
  shape:{ borderRadius:12 },
  typography:{ fontFamily:'Inter,Roboto,Helvetica Neue,Helvetica,Arial,sans-serif' },
});